language: python
python:
  - "pypy3.5"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "3.8-dev"
# command to install dependencies
install:
  - pip install setuptools pytest pytest-runner
  - pip install configargparse docutils
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
# command to run tests
script:
  - py.test
