language: python
python:
  - "3.6"
  - "3.7-dev"
# command to install dependencies
install:
  - pip install setuptools pytest pytest-runner
  - pip install configargparse docutils
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
# command to run tests
script:
  - py.test
