language: python
python:
  - "3.6"
  - "3.7-dev"
  - "3.8-dev"
# command to install dependencies
install:
  - pip install setuptools pytest pytest-runner
# command to run tests
script:
  - python3 setup.py test
