language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
# command to install dependencies
install:
  - pip install setuptools pytest pytest-runner relatorio
  - pip install configargparse docutils
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
# command to run tests
script:
  - py.test
