#!/bin/bash

_tdtlist_completions()
{
	candidates=""
	for candidate in `tdtproj -l $2`; do
		candidates="$candidates $candidate"
	done

	COMPREPLY=($(compgen -W "$candidates" $2))
}

complete -F _tdtlist_completions tdtlist
